### ISSUE TITLE
URL formatting and link to HCI Web docs

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#39]
* This can't be clicked on: "https://<_ManagementNodeIP_>". Of course it wouldn't work even if it was properly formatted https://127.0.0.1, but at least clickin on the loopback link helps you open a browser, whereas the first link does not. I'd suggest to use valid URLs, such as https://mNodeIp/ so that they can at least be clicked on
* "For details, see Accessing NetApp Hybrid Cloud Control." - now it links to HCI v.1.7.0 and 1.7.1 just came out. I wonder if there's a way to generalize (maybe by sending them to a page with search results for "Accessing NetApp Hybrid Cloud Control"?) these link to avoid having to constantly update them? It'd be nice if that site allowed `&v=latest` which would be even better.

Page: [Enabling cloud services](https://docs.netapp.com/us-en/hci/docs/task_enabling_cloud_services.html)

**Comment by amgrissino** [comment]
Sean, thank you again! For your 2nd comment, I've emailed a few folks and cc'd you on that email. We'll see what we can do to help this one. 

For your first comment, we do the same thing in the user guides and indicate that it's a variable. Prefer to provide as a variable so that people aren't clicking links that do not go anywhere or go to locations that don't have relevance.

**Comment by amgrissino** [comment]
For 2nd comment, we're investigating some options. Meanwhile, I've changed the link. 
Closing this. 
Thanks again, Sean! You are so everywhere! We are grateful for everything that you do!
